// <auto-generated />
using System;
using EasyDDD.Infrastructure.Data.DbContexts.BoundedContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyDDD.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231014135937_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AI")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyDDD.Domain.SystemVersions.SystemVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("Major")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<int>("Minor")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<int>("Patch")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("PreRelease")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Version", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
